// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	repositories "audioTest/src/interfaces/repositories"

	mock "github.com/stretchr/testify/mock"
)

// DbHandler is an autogenerated mock type for the DbHandler type
type DbHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: statement
func (_m *DbHandler) Execute(statement string) {
	_m.Called(statement)
}

// Query provides a mock function with given fields: statement
func (_m *DbHandler) Query(statement string) repositories.Row {
	ret := _m.Called(statement)

	var r0 repositories.Row
	if rf, ok := ret.Get(0).(func(string) repositories.Row); ok {
		r0 = rf(statement)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.Row)
		}
	}

	return r0
}
