// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileSystem is an autogenerated mock type for the FileSystem type
type FileSystem struct {
	mock.Mock
}

// Write provides a mock function with given fields: file, fileName
func (_m *FileSystem) Write(file []byte, fileName string) error {
	ret := _m.Called(file, fileName)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, string) error); ok {
		r0 = rf(file, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
