// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "audioTest/src/domain"

	mock "github.com/stretchr/testify/mock"
)

// IAudioRepository is an autogenerated mock type for the IAudioRepository type
type IAudioRepository struct {
	mock.Mock
}

// GetAudioInfo provides a mock function with given fields: _a0
func (_m *IAudioRepository) GetAudioInfo(_a0 string) (*domain.Audio, error) {
	ret := _m.Called(_a0)

	var r0 *domain.Audio
	if rf, ok := ret.Get(0).(func(string) *domain.Audio); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Audio)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreFile provides a mock function with given fields: _a0, _a1
func (_m *IAudioRepository) StoreFile(_a0 []byte, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
