// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// INats is an autogenerated mock type for the INats type
type INats struct {
	mock.Mock
}

// Publish provides a mock function with given fields: subject, message
func (_m *INats) Publish(subject string, message []byte) error {
	ret := _m.Called(subject, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(subject, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewINats interface {
	mock.TestingT
	Cleanup(func())
}

// NewINats creates a new instance of INats. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewINats(t mockConstructorTestingTNewINats) *INats {
	mock := &INats{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
